export const ASIAN_COUNTRIES = [
  { value: "Afghan", label: "Afghan" },
  { value: "Armenian", label: "Armenian" },
  { value: "Azerbaijani", label: "Azerbaijani" },
  { value: "Bahraini", label: "Bahraini" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Bhutanese", label: "Bhutanese" },
  { value: "Bruneian", label: "Bruneian" },
  { value: "Burmese", label: "Burmese" },
  { value: "Cambodian", label: "Cambodian" },
  { value: "Chinese", label: "Chinese" },
  { value: "Cypriot", label: "Cypriot" },
  { value: "East Timorese", label: "East Timorese" },
  { value: "Filipino", label: "Filipino" },
  { value: "Georgian", label: "Georgian" },
  { value: "Indian", label: "Indian" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Iranian", label: "Iranian" },
  { value: "Iraqi", label: "Iraqi" },
  { value: "Israeli", label: "Israeli" },
  { value: "Japanese", label: "Japanese" },
  { value: "Jordanian", label: "Jordanian" },
  { value: "Kazakh", label: "Kazakh" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Kyrgyz", label: "Kyrgyz" },
  { value: "Laotian", label: "Laotian" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Maldivian", label: "Maldivian" },
  { value: "Mongolian", label: "Mongolian" },
  { value: "Nepalese", label: "Nepalese" },
  { value: "North Korean", label: "North Korean" },
  { value: "Omani", label: "Omani" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Palestinian", label: "Palestinian" },
  { value: "Qatari", label: "Qatari" },
  { value: "Saudi", label: "Saudi" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "South Korean", label: "South Korean" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Syrian", label: "Syrian" },
  { value: "Taiwanese", label: "Taiwanese" },
  { value: "Tajik", label: "Tajik" },
  { value: "Thai", label: "Thai" },
  { value: "Turkish", label: "Turkish" },
  { value: "Turkmen", label: "Turkmen" },
  { value: "Emirati", label: "Emirati" },
  { value: "Uzbek", label: "Uzbek" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Yemeni", label: "Yemeni" },
] as const;
